### ISSUE TITLE
corona-stats.online

### ISSUE THREAD

**Issue by Berkmann18** [postmanlabs/covid-19-apis#276]
A worldwide rank table with live updates.

**Comment by kinlane** [comment]
Adding to list to create a Postman collection. We will need the Postman collection before we can add to the list.

**Comment by arlemi** [comment]
This is a CLI rather than an API. It surfaces data from APIs that we already have listed (e.g. [NovelCovidAPI](https://documenter.getpostman.com/view/11144369/Szf6Z9B3?version=latest)). I was going to recommend to list it on the [awesome-coronavirus list](https://github.com/soroushchehresa/awesome-coronavirus#cli) but I see it's already there so I'll go ahead and close this one. :)
